-- donto Lean overlay — root module re-exports.
import Donto.Core
import Donto.Predicates
import Donto.Truth
import Donto.Temporal
import Donto.IR
import Donto.Shapes
import Donto.Rules
import Donto.Certificate
import Donto.Engine
import Donto.Scope
import Donto.Correction
import Donto.SameMeaning
import Donto.Hypothesis
import Donto.Canonicals
import Donto.Evidence
import Donto.Argumentation
import Donto.Obligations
import Donto.Theorems
